version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - ./ssh_config:/etc/ssh/ssh_config
       - ./config/:/home/oxidized/.config/oxidized/